name: tio
version: 1.1.0
repository: https://github.com/urusai88/tio

description: |
  A simple wrapper for dio with response typing and full backward compatibility.
  Inspired by chopper.

topics:
  - dio
  - api
  - client
  - rest

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.0.0
  dio: ^5.4.0

dev_dependencies:
  lints: any
  test: ^1.5.0
  equatable: ^2.0.0
  collection: any