targets:
  $default:
    sources:
      exclude:
        - example

builders:
  tio_openapi_generator:
    import: package:tio_openapi_generator/builder.dart
    builder_factories:
      - tioOpenApiClientBuilder
    build_extensions: { }
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        - openapi.yaml
      options:
        configs:
          main:
            openapi: openapi.yaml
